//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SPCASW.Common", "FK_CampaignRecipients_CampaignID", "Campaigns", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SPCASW.Common.Campaign), "CampaignRecipients", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SPCASW.Common.CampaignRecipient), true)]
[assembly: EdmRelationshipAttribute("SPCASW.Common", "FK_CampaignRecipients_ContactID", "Contacts", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SPCASW.Common.Contact), "CampaignRecipients", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SPCASW.Common.CampaignRecipient), true)]

#endregion

namespace SPCASW.Common
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SPCAContactsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SPCAContactsEntities object using the connection string found in the 'SPCAContactsEntities' section of the application configuration file.
        /// </summary>
        public SPCAContactsEntities() : base("name=SPCAContactsEntities", "SPCAContactsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SPCAContactsEntities object.
        /// </summary>
        public SPCAContactsEntities(string connectionString) : base(connectionString, "SPCAContactsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SPCAContactsEntities object.
        /// </summary>
        public SPCAContactsEntities(EntityConnection connection) : base(connection, "SPCAContactsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CampaignRecipient> CampaignRecipients
        {
            get
            {
                if ((_CampaignRecipients == null))
                {
                    _CampaignRecipients = base.CreateObjectSet<CampaignRecipient>("CampaignRecipients");
                }
                return _CampaignRecipients;
            }
        }
        private ObjectSet<CampaignRecipient> _CampaignRecipients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Campaign> Campaigns
        {
            get
            {
                if ((_Campaigns == null))
                {
                    _Campaigns = base.CreateObjectSet<Campaign>("Campaigns");
                }
                return _Campaigns;
            }
        }
        private ObjectSet<Campaign> _Campaigns;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Contact> Contacts
        {
            get
            {
                if ((_Contacts == null))
                {
                    _Contacts = base.CreateObjectSet<Contact>("Contacts");
                }
                return _Contacts;
            }
        }
        private ObjectSet<Contact> _Contacts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Contacts_temp> Contacts_temp
        {
            get
            {
                if ((_Contacts_temp == null))
                {
                    _Contacts_temp = base.CreateObjectSet<Contacts_temp>("Contacts_temp");
                }
                return _Contacts_temp;
            }
        }
        private ObjectSet<Contacts_temp> _Contacts_temp;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CampaignRecipients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCampaignRecipients(CampaignRecipient campaignRecipient)
        {
            base.AddObject("CampaignRecipients", campaignRecipient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Campaigns EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCampaigns(Campaign campaign)
        {
            base.AddObject("Campaigns", campaign);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Contacts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContacts(Contact contact)
        {
            base.AddObject("Contacts", contact);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Contacts_temp EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContacts_temp(Contacts_temp contacts_temp)
        {
            base.AddObject("Contacts_temp", contacts_temp);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SPCASW.Common", Name="Campaign")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Campaign : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Campaign object.
        /// </summary>
        /// <param name="campaignID">Initial value of the CampaignID property.</param>
        public static Campaign CreateCampaign(global::System.Int32 campaignID)
        {
            Campaign campaign = new Campaign();
            campaign.CampaignID = campaignID;
            return campaign;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CampaignID
        {
            get
            {
                return _CampaignID;
            }
            set
            {
                if (_CampaignID != value)
                {
                    OnCampaignIDChanging(value);
                    ReportPropertyChanging("CampaignID");
                    _CampaignID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CampaignID");
                    OnCampaignIDChanged();
                }
            }
        }
        private global::System.Int32 _CampaignID;
        partial void OnCampaignIDChanging(global::System.Int32 value);
        partial void OnCampaignIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CampaignName
        {
            get
            {
                return _CampaignName;
            }
            set
            {
                OnCampaignNameChanging(value);
                ReportPropertyChanging("CampaignName");
                _CampaignName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CampaignName");
                OnCampaignNameChanged();
            }
        }
        private global::System.String _CampaignName;
        partial void OnCampaignNameChanging(global::System.String value);
        partial void OnCampaignNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private Nullable<global::System.Guid> _CreatedBy;
        partial void OnCreatedByChanging(Nullable<global::System.Guid> value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedOn;
        partial void OnCreatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedOnChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SPCASW.Common", "FK_CampaignRecipients_CampaignID", "CampaignRecipients")]
        public EntityCollection<CampaignRecipient> CampaignRecipients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CampaignRecipient>("SPCASW.Common.FK_CampaignRecipients_CampaignID", "CampaignRecipients");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CampaignRecipient>("SPCASW.Common.FK_CampaignRecipients_CampaignID", "CampaignRecipients", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SPCASW.Common", Name="CampaignRecipient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CampaignRecipient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CampaignRecipient object.
        /// </summary>
        /// <param name="campaignRecipientID">Initial value of the CampaignRecipientID property.</param>
        /// <param name="campaignID">Initial value of the CampaignID property.</param>
        /// <param name="contactID">Initial value of the ContactID property.</param>
        public static CampaignRecipient CreateCampaignRecipient(global::System.Int32 campaignRecipientID, global::System.Int32 campaignID, global::System.Int32 contactID)
        {
            CampaignRecipient campaignRecipient = new CampaignRecipient();
            campaignRecipient.CampaignRecipientID = campaignRecipientID;
            campaignRecipient.CampaignID = campaignID;
            campaignRecipient.ContactID = contactID;
            return campaignRecipient;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CampaignRecipientID
        {
            get
            {
                return _CampaignRecipientID;
            }
            set
            {
                if (_CampaignRecipientID != value)
                {
                    OnCampaignRecipientIDChanging(value);
                    ReportPropertyChanging("CampaignRecipientID");
                    _CampaignRecipientID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CampaignRecipientID");
                    OnCampaignRecipientIDChanged();
                }
            }
        }
        private global::System.Int32 _CampaignRecipientID;
        partial void OnCampaignRecipientIDChanging(global::System.Int32 value);
        partial void OnCampaignRecipientIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CampaignID
        {
            get
            {
                return _CampaignID;
            }
            set
            {
                OnCampaignIDChanging(value);
                ReportPropertyChanging("CampaignID");
                _CampaignID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CampaignID");
                OnCampaignIDChanged();
            }
        }
        private global::System.Int32 _CampaignID;
        partial void OnCampaignIDChanging(global::System.Int32 value);
        partial void OnCampaignIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContactID
        {
            get
            {
                return _ContactID;
            }
            set
            {
                OnContactIDChanging(value);
                ReportPropertyChanging("ContactID");
                _ContactID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContactID");
                OnContactIDChanged();
            }
        }
        private global::System.Int32 _ContactID;
        partial void OnContactIDChanging(global::System.Int32 value);
        partial void OnContactIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SPCASW.Common", "FK_CampaignRecipients_CampaignID", "Campaigns")]
        public Campaign Campaign
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Campaign>("SPCASW.Common.FK_CampaignRecipients_CampaignID", "Campaigns").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Campaign>("SPCASW.Common.FK_CampaignRecipients_CampaignID", "Campaigns").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Campaign> CampaignReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Campaign>("SPCASW.Common.FK_CampaignRecipients_CampaignID", "Campaigns");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Campaign>("SPCASW.Common.FK_CampaignRecipients_CampaignID", "Campaigns", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SPCASW.Common", "FK_CampaignRecipients_ContactID", "Contacts")]
        public Contact Contact
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contact>("SPCASW.Common.FK_CampaignRecipients_ContactID", "Contacts").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contact>("SPCASW.Common.FK_CampaignRecipients_ContactID", "Contacts").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Contact> ContactReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contact>("SPCASW.Common.FK_CampaignRecipients_ContactID", "Contacts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Contact>("SPCASW.Common.FK_CampaignRecipients_ContactID", "Contacts", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SPCASW.Common", Name="Contact")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Contact : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Contact object.
        /// </summary>
        /// <param name="contactID">Initial value of the ContactID property.</param>
        /// <param name="isVolunteer">Initial value of the IsVolunteer property.</param>
        /// <param name="isDonor">Initial value of the IsDonor property.</param>
        /// <param name="isAdopter">Initial value of the IsAdopter property.</param>
        /// <param name="isEmailAllowed">Initial value of the IsEmailAllowed property.</param>
        /// <param name="isMailAllowed">Initial value of the IsMailAllowed property.</param>
        /// <param name="isMailAddressValid">Initial value of the IsMailAddressValid property.</param>
        public static Contact CreateContact(global::System.Int32 contactID, global::System.Boolean isVolunteer, global::System.Boolean isDonor, global::System.Boolean isAdopter, global::System.Boolean isEmailAllowed, global::System.Boolean isMailAllowed, global::System.Boolean isMailAddressValid)
        {
            Contact contact = new Contact();
            contact.ContactID = contactID;
            contact.IsVolunteer = isVolunteer;
            contact.IsDonor = isDonor;
            contact.IsAdopter = isAdopter;
            contact.IsEmailAllowed = isEmailAllowed;
            contact.IsMailAllowed = isMailAllowed;
            contact.IsMailAddressValid = isMailAddressValid;
            return contact;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContactID
        {
            get
            {
                return _ContactID;
            }
            set
            {
                if (_ContactID != value)
                {
                    OnContactIDChanging(value);
                    ReportPropertyChanging("ContactID");
                    _ContactID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ContactID");
                    OnContactIDChanged();
                }
            }
        }
        private global::System.Int32 _ContactID;
        partial void OnContactIDChanging(global::System.Int32 value);
        partial void OnContactIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsVolunteer
        {
            get
            {
                return _IsVolunteer;
            }
            set
            {
                OnIsVolunteerChanging(value);
                ReportPropertyChanging("IsVolunteer");
                _IsVolunteer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsVolunteer");
                OnIsVolunteerChanged();
            }
        }
        private global::System.Boolean _IsVolunteer;
        partial void OnIsVolunteerChanging(global::System.Boolean value);
        partial void OnIsVolunteerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDonor
        {
            get
            {
                return _IsDonor;
            }
            set
            {
                OnIsDonorChanging(value);
                ReportPropertyChanging("IsDonor");
                _IsDonor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDonor");
                OnIsDonorChanged();
            }
        }
        private global::System.Boolean _IsDonor;
        partial void OnIsDonorChanging(global::System.Boolean value);
        partial void OnIsDonorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAdopter
        {
            get
            {
                return _IsAdopter;
            }
            set
            {
                OnIsAdopterChanging(value);
                ReportPropertyChanging("IsAdopter");
                _IsAdopter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAdopter");
                OnIsAdopterChanged();
            }
        }
        private global::System.Boolean _IsAdopter;
        partial void OnIsAdopterChanging(global::System.Boolean value);
        partial void OnIsAdopterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StateCode
        {
            get
            {
                return _StateCode;
            }
            set
            {
                OnStateCodeChanging(value);
                ReportPropertyChanging("StateCode");
                _StateCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StateCode");
                OnStateCodeChanged();
            }
        }
        private global::System.String _StateCode;
        partial void OnStateCodeChanging(global::System.String value);
        partial void OnStateCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PostalCode
        {
            get
            {
                return _PostalCode;
            }
            set
            {
                OnPostalCodeChanging(value);
                ReportPropertyChanging("PostalCode");
                _PostalCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PostalCode");
                OnPostalCodeChanged();
            }
        }
        private global::System.String _PostalCode;
        partial void OnPostalCodeChanging(global::System.String value);
        partial void OnPostalCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsEmailAllowed
        {
            get
            {
                return _IsEmailAllowed;
            }
            set
            {
                OnIsEmailAllowedChanging(value);
                ReportPropertyChanging("IsEmailAllowed");
                _IsEmailAllowed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEmailAllowed");
                OnIsEmailAllowedChanged();
            }
        }
        private global::System.Boolean _IsEmailAllowed;
        partial void OnIsEmailAllowedChanging(global::System.Boolean value);
        partial void OnIsEmailAllowedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsMailAllowed
        {
            get
            {
                return _IsMailAllowed;
            }
            set
            {
                OnIsMailAllowedChanging(value);
                ReportPropertyChanging("IsMailAllowed");
                _IsMailAllowed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsMailAllowed");
                OnIsMailAllowedChanged();
            }
        }
        private global::System.Boolean _IsMailAllowed;
        partial void OnIsMailAllowedChanging(global::System.Boolean value);
        partial void OnIsMailAllowedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsMailAddressValid
        {
            get
            {
                return _IsMailAddressValid;
            }
            set
            {
                OnIsMailAddressValidChanging(value);
                ReportPropertyChanging("IsMailAddressValid");
                _IsMailAddressValid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsMailAddressValid");
                OnIsMailAddressValidChanged();
            }
        }
        private global::System.Boolean _IsMailAddressValid;
        partial void OnIsMailAddressValidChanging(global::System.Boolean value);
        partial void OnIsMailAddressValidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PetPointID
        {
            get
            {
                return _PetPointID;
            }
            set
            {
                OnPetPointIDChanging(value);
                ReportPropertyChanging("PetPointID");
                _PetPointID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PetPointID");
                OnPetPointIDChanged();
            }
        }
        private global::System.String _PetPointID;
        partial void OnPetPointIDChanging(global::System.String value);
        partial void OnPetPointIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private Nullable<global::System.Guid> _CreatedBy;
        partial void OnCreatedByChanging(Nullable<global::System.Guid> value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedOn;
        partial void OnCreatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StreetAddress1
        {
            get
            {
                return _StreetAddress1;
            }
            set
            {
                OnStreetAddress1Changing(value);
                ReportPropertyChanging("StreetAddress1");
                _StreetAddress1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StreetAddress1");
                OnStreetAddress1Changed();
            }
        }
        private global::System.String _StreetAddress1;
        partial void OnStreetAddress1Changing(global::System.String value);
        partial void OnStreetAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StreetAddress2
        {
            get
            {
                return _StreetAddress2;
            }
            set
            {
                OnStreetAddress2Changing(value);
                ReportPropertyChanging("StreetAddress2");
                _StreetAddress2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StreetAddress2");
                OnStreetAddress2Changed();
            }
        }
        private global::System.String _StreetAddress2;
        partial void OnStreetAddress2Changing(global::System.String value);
        partial void OnStreetAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone1
        {
            get
            {
                return _Phone1;
            }
            set
            {
                OnPhone1Changing(value);
                ReportPropertyChanging("Phone1");
                _Phone1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone1");
                OnPhone1Changed();
            }
        }
        private global::System.String _Phone1;
        partial void OnPhone1Changing(global::System.String value);
        partial void OnPhone1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneType1
        {
            get
            {
                return _PhoneType1;
            }
            set
            {
                OnPhoneType1Changing(value);
                ReportPropertyChanging("PhoneType1");
                _PhoneType1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneType1");
                OnPhoneType1Changed();
            }
        }
        private global::System.String _PhoneType1;
        partial void OnPhoneType1Changing(global::System.String value);
        partial void OnPhoneType1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone2
        {
            get
            {
                return _Phone2;
            }
            set
            {
                OnPhone2Changing(value);
                ReportPropertyChanging("Phone2");
                _Phone2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone2");
                OnPhone2Changed();
            }
        }
        private global::System.String _Phone2;
        partial void OnPhone2Changing(global::System.String value);
        partial void OnPhone2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneType2
        {
            get
            {
                return _PhoneType2;
            }
            set
            {
                OnPhoneType2Changing(value);
                ReportPropertyChanging("PhoneType2");
                _PhoneType2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneType2");
                OnPhoneType2Changed();
            }
        }
        private global::System.String _PhoneType2;
        partial void OnPhoneType2Changing(global::System.String value);
        partial void OnPhoneType2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone3
        {
            get
            {
                return _Phone3;
            }
            set
            {
                OnPhone3Changing(value);
                ReportPropertyChanging("Phone3");
                _Phone3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone3");
                OnPhone3Changed();
            }
        }
        private global::System.String _Phone3;
        partial void OnPhone3Changing(global::System.String value);
        partial void OnPhone3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneType3
        {
            get
            {
                return _PhoneType3;
            }
            set
            {
                OnPhoneType3Changing(value);
                ReportPropertyChanging("PhoneType3");
                _PhoneType3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneType3");
                OnPhoneType3Changed();
            }
        }
        private global::System.String _PhoneType3;
        partial void OnPhoneType3Changing(global::System.String value);
        partial void OnPhoneType3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone4
        {
            get
            {
                return _Phone4;
            }
            set
            {
                OnPhone4Changing(value);
                ReportPropertyChanging("Phone4");
                _Phone4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone4");
                OnPhone4Changed();
            }
        }
        private global::System.String _Phone4;
        partial void OnPhone4Changing(global::System.String value);
        partial void OnPhone4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneType4
        {
            get
            {
                return _PhoneType4;
            }
            set
            {
                OnPhoneType4Changing(value);
                ReportPropertyChanging("PhoneType4");
                _PhoneType4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneType4");
                OnPhoneType4Changed();
            }
        }
        private global::System.String _PhoneType4;
        partial void OnPhoneType4Changing(global::System.String value);
        partial void OnPhoneType4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private Nullable<global::System.Guid> _ModifiedBy;
        partial void OnModifiedByChanging(Nullable<global::System.Guid> value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedOn
        {
            get
            {
                return _ModifiedOn;
            }
            set
            {
                OnModifiedOnChanging(value);
                ReportPropertyChanging("ModifiedOn");
                _ModifiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedOn");
                OnModifiedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedOn;
        partial void OnModifiedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SPCASW.Common", "FK_CampaignRecipients_ContactID", "CampaignRecipients")]
        public EntityCollection<CampaignRecipient> CampaignRecipients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CampaignRecipient>("SPCASW.Common.FK_CampaignRecipients_ContactID", "CampaignRecipients");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CampaignRecipient>("SPCASW.Common.FK_CampaignRecipients_ContactID", "CampaignRecipients", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SPCASW.Common", Name="Contacts_temp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Contacts_temp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Contacts_temp object.
        /// </summary>
        /// <param name="contactID">Initial value of the ContactID property.</param>
        /// <param name="isVolunteer">Initial value of the IsVolunteer property.</param>
        /// <param name="isDonor">Initial value of the IsDonor property.</param>
        /// <param name="isAdopter">Initial value of the IsAdopter property.</param>
        /// <param name="isEmailAllowed">Initial value of the IsEmailAllowed property.</param>
        /// <param name="isMailAllowed">Initial value of the IsMailAllowed property.</param>
        /// <param name="isMailAddressValid">Initial value of the IsMailAddressValid property.</param>
        public static Contacts_temp CreateContacts_temp(global::System.Int32 contactID, global::System.Boolean isVolunteer, global::System.Boolean isDonor, global::System.Boolean isAdopter, global::System.Boolean isEmailAllowed, global::System.Boolean isMailAllowed, global::System.Boolean isMailAddressValid)
        {
            Contacts_temp contacts_temp = new Contacts_temp();
            contacts_temp.ContactID = contactID;
            contacts_temp.IsVolunteer = isVolunteer;
            contacts_temp.IsDonor = isDonor;
            contacts_temp.IsAdopter = isAdopter;
            contacts_temp.IsEmailAllowed = isEmailAllowed;
            contacts_temp.IsMailAllowed = isMailAllowed;
            contacts_temp.IsMailAddressValid = isMailAddressValid;
            return contacts_temp;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContactID
        {
            get
            {
                return _ContactID;
            }
            set
            {
                if (_ContactID != value)
                {
                    OnContactIDChanging(value);
                    ReportPropertyChanging("ContactID");
                    _ContactID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ContactID");
                    OnContactIDChanged();
                }
            }
        }
        private global::System.Int32 _ContactID;
        partial void OnContactIDChanging(global::System.Int32 value);
        partial void OnContactIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsVolunteer
        {
            get
            {
                return _IsVolunteer;
            }
            set
            {
                OnIsVolunteerChanging(value);
                ReportPropertyChanging("IsVolunteer");
                _IsVolunteer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsVolunteer");
                OnIsVolunteerChanged();
            }
        }
        private global::System.Boolean _IsVolunteer;
        partial void OnIsVolunteerChanging(global::System.Boolean value);
        partial void OnIsVolunteerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDonor
        {
            get
            {
                return _IsDonor;
            }
            set
            {
                OnIsDonorChanging(value);
                ReportPropertyChanging("IsDonor");
                _IsDonor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDonor");
                OnIsDonorChanged();
            }
        }
        private global::System.Boolean _IsDonor;
        partial void OnIsDonorChanging(global::System.Boolean value);
        partial void OnIsDonorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAdopter
        {
            get
            {
                return _IsAdopter;
            }
            set
            {
                OnIsAdopterChanging(value);
                ReportPropertyChanging("IsAdopter");
                _IsAdopter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAdopter");
                OnIsAdopterChanged();
            }
        }
        private global::System.Boolean _IsAdopter;
        partial void OnIsAdopterChanging(global::System.Boolean value);
        partial void OnIsAdopterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StreetAddress1
        {
            get
            {
                return _StreetAddress1;
            }
            set
            {
                OnStreetAddress1Changing(value);
                ReportPropertyChanging("StreetAddress1");
                _StreetAddress1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StreetAddress1");
                OnStreetAddress1Changed();
            }
        }
        private global::System.String _StreetAddress1;
        partial void OnStreetAddress1Changing(global::System.String value);
        partial void OnStreetAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StreetAddress2
        {
            get
            {
                return _StreetAddress2;
            }
            set
            {
                OnStreetAddress2Changing(value);
                ReportPropertyChanging("StreetAddress2");
                _StreetAddress2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StreetAddress2");
                OnStreetAddress2Changed();
            }
        }
        private global::System.String _StreetAddress2;
        partial void OnStreetAddress2Changing(global::System.String value);
        partial void OnStreetAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StateCode
        {
            get
            {
                return _StateCode;
            }
            set
            {
                OnStateCodeChanging(value);
                ReportPropertyChanging("StateCode");
                _StateCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StateCode");
                OnStateCodeChanged();
            }
        }
        private global::System.String _StateCode;
        partial void OnStateCodeChanging(global::System.String value);
        partial void OnStateCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PostalCode
        {
            get
            {
                return _PostalCode;
            }
            set
            {
                OnPostalCodeChanging(value);
                ReportPropertyChanging("PostalCode");
                _PostalCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PostalCode");
                OnPostalCodeChanged();
            }
        }
        private global::System.String _PostalCode;
        partial void OnPostalCodeChanging(global::System.String value);
        partial void OnPostalCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone1
        {
            get
            {
                return _Phone1;
            }
            set
            {
                OnPhone1Changing(value);
                ReportPropertyChanging("Phone1");
                _Phone1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone1");
                OnPhone1Changed();
            }
        }
        private global::System.String _Phone1;
        partial void OnPhone1Changing(global::System.String value);
        partial void OnPhone1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneType1
        {
            get
            {
                return _PhoneType1;
            }
            set
            {
                OnPhoneType1Changing(value);
                ReportPropertyChanging("PhoneType1");
                _PhoneType1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneType1");
                OnPhoneType1Changed();
            }
        }
        private global::System.String _PhoneType1;
        partial void OnPhoneType1Changing(global::System.String value);
        partial void OnPhoneType1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone2
        {
            get
            {
                return _Phone2;
            }
            set
            {
                OnPhone2Changing(value);
                ReportPropertyChanging("Phone2");
                _Phone2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone2");
                OnPhone2Changed();
            }
        }
        private global::System.String _Phone2;
        partial void OnPhone2Changing(global::System.String value);
        partial void OnPhone2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneType2
        {
            get
            {
                return _PhoneType2;
            }
            set
            {
                OnPhoneType2Changing(value);
                ReportPropertyChanging("PhoneType2");
                _PhoneType2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneType2");
                OnPhoneType2Changed();
            }
        }
        private global::System.String _PhoneType2;
        partial void OnPhoneType2Changing(global::System.String value);
        partial void OnPhoneType2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone3
        {
            get
            {
                return _Phone3;
            }
            set
            {
                OnPhone3Changing(value);
                ReportPropertyChanging("Phone3");
                _Phone3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone3");
                OnPhone3Changed();
            }
        }
        private global::System.String _Phone3;
        partial void OnPhone3Changing(global::System.String value);
        partial void OnPhone3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneType3
        {
            get
            {
                return _PhoneType3;
            }
            set
            {
                OnPhoneType3Changing(value);
                ReportPropertyChanging("PhoneType3");
                _PhoneType3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneType3");
                OnPhoneType3Changed();
            }
        }
        private global::System.String _PhoneType3;
        partial void OnPhoneType3Changing(global::System.String value);
        partial void OnPhoneType3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone4
        {
            get
            {
                return _Phone4;
            }
            set
            {
                OnPhone4Changing(value);
                ReportPropertyChanging("Phone4");
                _Phone4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone4");
                OnPhone4Changed();
            }
        }
        private global::System.String _Phone4;
        partial void OnPhone4Changing(global::System.String value);
        partial void OnPhone4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneType4
        {
            get
            {
                return _PhoneType4;
            }
            set
            {
                OnPhoneType4Changing(value);
                ReportPropertyChanging("PhoneType4");
                _PhoneType4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneType4");
                OnPhoneType4Changed();
            }
        }
        private global::System.String _PhoneType4;
        partial void OnPhoneType4Changing(global::System.String value);
        partial void OnPhoneType4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsEmailAllowed
        {
            get
            {
                return _IsEmailAllowed;
            }
            set
            {
                OnIsEmailAllowedChanging(value);
                ReportPropertyChanging("IsEmailAllowed");
                _IsEmailAllowed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEmailAllowed");
                OnIsEmailAllowedChanged();
            }
        }
        private global::System.Boolean _IsEmailAllowed;
        partial void OnIsEmailAllowedChanging(global::System.Boolean value);
        partial void OnIsEmailAllowedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsMailAllowed
        {
            get
            {
                return _IsMailAllowed;
            }
            set
            {
                OnIsMailAllowedChanging(value);
                ReportPropertyChanging("IsMailAllowed");
                _IsMailAllowed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsMailAllowed");
                OnIsMailAllowedChanged();
            }
        }
        private global::System.Boolean _IsMailAllowed;
        partial void OnIsMailAllowedChanging(global::System.Boolean value);
        partial void OnIsMailAllowedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsMailAddressValid
        {
            get
            {
                return _IsMailAddressValid;
            }
            set
            {
                OnIsMailAddressValidChanging(value);
                ReportPropertyChanging("IsMailAddressValid");
                _IsMailAddressValid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsMailAddressValid");
                OnIsMailAddressValidChanged();
            }
        }
        private global::System.Boolean _IsMailAddressValid;
        partial void OnIsMailAddressValidChanging(global::System.Boolean value);
        partial void OnIsMailAddressValidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PetPointID
        {
            get
            {
                return _PetPointID;
            }
            set
            {
                OnPetPointIDChanging(value);
                ReportPropertyChanging("PetPointID");
                _PetPointID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PetPointID");
                OnPetPointIDChanged();
            }
        }
        private global::System.String _PetPointID;
        partial void OnPetPointIDChanging(global::System.String value);
        partial void OnPetPointIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private Nullable<global::System.Guid> _CreatedBy;
        partial void OnCreatedByChanging(Nullable<global::System.Guid> value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedOn;
        partial void OnCreatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();

        #endregion

    
    }

    #endregion

    
}
